# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\ngrpc.proto\"G\n\nXmlMessage\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\x05\x12\x12\n\nrawMessage\x18\x02 \x01(\t\x12\x14\n\x0cparsedInJava\x18\x03 \x01(\x08\"\x16\n\x05\x42ooly\x12\r\n\x05value\x18\x01 \x01(\x08\"A\n\x0c\x43ontrolEvent\x12\x1e\n\x05value\x18\x01 \x01(\x0e\x32\x0f.ControlMessage\x12\x11\n\ttimestamp\x18\x02 \x01(\x03*3\n\x0e\x43ontrolMessage\x12\t\n\x05\x41\x42ORT\x10\x00\x12\t\n\x05PAUSE\x10\x01\x12\x0b\n\x07RELEASE\x10\x02\x32s\n\x14ServerMessagesStream\x12+\n\x10registerListener\x12\x06.Booly\x1a\x0b.XmlMessage\"\x00\x30\x01\x12.\n\x13registerEventSource\x12\x0b.XmlMessage\x1a\x06.Booly\"\x00(\x01\x32\x44\n\x13\x43ontrolEventHandler\x12-\n\x12submitControlEvent\x12\r.ControlEvent\x1a\x06.Booly\"\x00\x42\"\n\x1eorg.powertac.samplebroker.grpcP\x01\x62\x06proto3')
)

_CONTROLMESSAGE = _descriptor.EnumDescriptor(
  name='ControlMessage',
  full_name='ControlMessage',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ABORT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAUSE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELEASE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=178,
  serialized_end=229,
)
_sym_db.RegisterEnumDescriptor(_CONTROLMESSAGE)

ControlMessage = enum_type_wrapper.EnumTypeWrapper(_CONTROLMESSAGE)
ABORT = 0
PAUSE = 1
RELEASE = 2



_XMLMESSAGE = _descriptor.Descriptor(
  name='XmlMessage',
  full_name='XmlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='counter', full_name='XmlMessage.counter', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rawMessage', full_name='XmlMessage.rawMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parsedInJava', full_name='XmlMessage.parsedInJava', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=85,
)


_BOOLY = _descriptor.Descriptor(
  name='Booly',
  full_name='Booly',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Booly.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=109,
)


_CONTROLEVENT = _descriptor.Descriptor(
  name='ControlEvent',
  full_name='ControlEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ControlEvent.value', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ControlEvent.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=176,
)

_CONTROLEVENT.fields_by_name['value'].enum_type = _CONTROLMESSAGE
DESCRIPTOR.message_types_by_name['XmlMessage'] = _XMLMESSAGE
DESCRIPTOR.message_types_by_name['Booly'] = _BOOLY
DESCRIPTOR.message_types_by_name['ControlEvent'] = _CONTROLEVENT
DESCRIPTOR.enum_types_by_name['ControlMessage'] = _CONTROLMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XmlMessage = _reflection.GeneratedProtocolMessageType('XmlMessage', (_message.Message,), dict(
  DESCRIPTOR = _XMLMESSAGE,
  __module__ = 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:XmlMessage)
  ))
_sym_db.RegisterMessage(XmlMessage)

Booly = _reflection.GeneratedProtocolMessageType('Booly', (_message.Message,), dict(
  DESCRIPTOR = _BOOLY,
  __module__ = 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:Booly)
  ))
_sym_db.RegisterMessage(Booly)

ControlEvent = _reflection.GeneratedProtocolMessageType('ControlEvent', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLEVENT,
  __module__ = 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:ControlEvent)
  ))
_sym_db.RegisterMessage(ControlEvent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036org.powertac.samplebroker.grpcP\001'))

_SERVERMESSAGESSTREAM = _descriptor.ServiceDescriptor(
  name='ServerMessagesStream',
  full_name='ServerMessagesStream',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=231,
  serialized_end=346,
  methods=[
  _descriptor.MethodDescriptor(
    name='registerListener',
    full_name='ServerMessagesStream.registerListener',
    index=0,
    containing_service=None,
    input_type=_BOOLY,
    output_type=_XMLMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='registerEventSource',
    full_name='ServerMessagesStream.registerEventSource',
    index=1,
    containing_service=None,
    input_type=_XMLMESSAGE,
    output_type=_BOOLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERMESSAGESSTREAM)

DESCRIPTOR.services_by_name['ServerMessagesStream'] = _SERVERMESSAGESSTREAM


_CONTROLEVENTHANDLER = _descriptor.ServiceDescriptor(
  name='ControlEventHandler',
  full_name='ControlEventHandler',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=348,
  serialized_end=416,
  methods=[
  _descriptor.MethodDescriptor(
    name='submitControlEvent',
    full_name='ControlEventHandler.submitControlEvent',
    index=0,
    containing_service=None,
    input_type=_CONTROLEVENT,
    output_type=_BOOLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLEVENTHANDLER)

DESCRIPTOR.services_by_name['ControlEventHandler'] = _CONTROLEVENTHANDLER

# @@protoc_insertion_point(module_scope)
